version: "3.8"
services:
  api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: 
    #   - .env
    ports:
      - "4000:4000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    depends_on:
      - mongo
    # network_mode: service:mongo

  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - ./:/data
    ports:
      - "27019:27017"

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]